### ISSUE TITLE
can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by hobocow** [thebotsmith/Excelsior-Milano-raffle#4]
![image](https://user-images.githubusercontent.com/8590048/43497491-c08a8220-9542-11e8-9eaf-d427b24dcb83.png)

getting the error above, i'm using python 2.7.15, not sure what the problem is, also enteredaccounts.txt is blank.

**Comment by hobocow** [comment]
removed the comma after (getrandbits(40)) working now

**Comment by mapooo** [comment]
You can fork the code with your edit and add a pull request to contribute your fix
